# Generated by Django 5.0.6 on 2024-06-15 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_snippet_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['name', 'lang']},
        ),
    ]
